spring.application.name=correctratelogmigrationservice
spring.datasource.url=jdbc:mysql://db:3306/correctratelog_db
spring.datasource.username=
spring.datasource.password=
spring.main.allow-bean-definition-overriding=true