spring.application.name=correctratelogmigrationservice
spring.datasource.url=jdbc:mysql://db:3306/correctratelog_db
spring.datasource.username=ratelogger
spring.datasource.password=correct
spring.sql.init.mode=always