services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 49152:8080

  db:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: correct
      MYSQL_DATABASE: correctratelog_db
      MYSQL_USER: ratelogger
      MYSQL_PASSWORD: correct
    command: ["mysqld", "--character-set-server=utf8mb4"]
    volumes:
      - db-bk:/var/lib/mysql

  java:
    build: 
      context: .
      dockerfile: JavaDockerfile
    command: sleep infinity 
    volumes:
      - ../workspace:/workspace
    ports:
      - 8080:8080

volumes:
  db-bk:
