services:
  db:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MySQL_USER: 
      MYSQL_PASSWORD: 
    command: ["mysqld", "--character-set-server=utf8mb4"]
    volumes:
      - db-sample:/var/lib/mysql

  java:
    build: 
      context: .
      dockerfile: JavaDockerfile
    command: sleep infinity 
    volumes:
      - ../workspace:/workspace

volumes:
  db-sample:
